services:
  postgres:
    image: postgres:15
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  airflow-init:
    image: apache/airflow:2.9.2
    entrypoint: /bin/bash
    command: -c "pip install -r /opt/airflow/requirements.txt && airflow db init"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./requirements.txt:/opt/airflow/requirements.txt
  airflow-webserver:
    image: apache/airflow:2.9.2  
    env_file:
      - .env
    container_name: airflow.webserver
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTION: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./requirements.txt:/opt/airflow/requirements.txt
    ports:
      - "8080:8080"
    command: bash -c "pip install -r /opt/airflow/requirements.txt && airflow webserver"

  airflow_scheduler:
    image: apache/airflow:2.9.2
    develop:
      watch:
        - action: sync
          path: ./dags
          target: /opt/airflow/dags
        - action: sync
          path: ./src
          target: /opt/airflow/src

    env_file:
      - .env
    container_name: airflow.scheduler
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTION: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
    - ./dags:/opt/airflow/dags
    - ./src:/opt/airflow/src
    - ./requirements.txt:/opt/airflow/requirements.txt
    command: bash -c "pip install -r /opt/airflow/requirements.txt && airflow scheduler"

volumes:
  postgres_data:


